####docker-compose file
#
## version: "3"
## 
## services:
##   frontend:
##     image: ghcr.io/srini-ca/finsecops:latest
##     networks:
##       - frontend
##     ports:
##       - "80:3000"
## 
## networks:
##   frontend:
##     driver: bridge

---

####docker-stack/swarm file
#
version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    networks:
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend

  frontend:
    image: ghcr.io/srini-ca/finsecops:latest
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    networks:
      - frontend
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  frontend:
    driver: overlay